[package]
name = "libquil-sys"
description = "High-level bindings to libquil"
version = "0.5.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/rigetti/libquil-sys"
keywords = ["pyquil", "Quil", "libquil", "quilc", "QVM"]
links = "quilc"
build = "build.rs"
categories = ["compilers", "api-bindings"]
readme = "../README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { workspace = true }
libloading = { workspace = true }
num-complex = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
pastey = { workspace = true }

[build-dependencies]
cc = { workspace = true, features = ["parallel"] }
pkg-config = { workspace = true }
bindgen = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
quil-rs = { workspace = true }

