[package]
name = "libquil_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "libquil"
crate-type = ["cdylib", "rlib"]

[dependencies]
libloading = { workspace = true }
libquil-sys = { workspace = true }
# pyo3 dependencies should be updated together
numpy = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module"] }
rigetti-pyo3 = { workspace = true }

[build-dependencies]
pyo3-build-config = { workspace = true }
