name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: Bump versions and trigger a new release.
        required: true
        default: release
        options:
          - release

jobs:
  prepare-release:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Install Knope
      uses: knope-dev/action@v2.0.0
      with:
        version: 0.10.0 # Test before updating, breaking changes likely: https://github.com/knope-dev/action#install-latest-version
    - run: |
        git config --global user.name "${{ github.triggering_actor }}"
        git config --global user.email "${{ github.triggering_actor}}@users.noreply.github.com"
    - name: Prepare Release
      run: knope ${{ inputs.type }} --verbose
      if: github.event_name == 'workflow_dispatch'

